parameters:
    guzzle:
        timeout: "%guzzle.timeout%"
        connect_timeout: "%guzzle.connect_timeout%"

services:

#odm ==================================================================
    odm.hot.dbal:
       class: ODM\DBAL
       arguments:
           - "%database.hot.host%"
           - "%database.hot.port%"
           - "%database.hot.name%"
           
    odm.hot.data.mapper.factory:
       class: ODM\DocumentMapper\DataMapperFactory
       arguments:
           - "@odm.hot.dbal"

    odm.cold.dbal:
       class: ODM\DBAL
       arguments:
           - "%database.cold.host%"
           - "%database.cold.port%"
           - "%database.cold.name%"

    odm.cold.data.mapper.factory:
       class: ODM\DocumentMapper\DataMapperFactory
       arguments:
           - "@odm.cold.dbal"

#odm ==================================================================


#clients =============================================================

    client.http:
        class: AppBundle\Service\Client\Http
        arguments:
            - "%guzzle%"

#clients =============================================================


#parsers =============================================================

    parser.area.factory:
        class: AppBundle\Model\Parser\Area\AreaParserFactory
        arguments:
            - '%bin.tomita%'
            - '%file.config.tomita.area%'

    parser.contact.factory:
        class: AppBundle\Model\Parser\Contact\ContactParserFactory
        arguments:
            - '%bin.tomita%'
            - '%file.config.tomita.contact%'

    parser.type.factory:
        class: AppBundle\Model\Parser\Type\TypeParserFactory
        arguments:
            - '%bin.tomita%'
            - '%file.config.tomita.type%'

    parser.price.factory:
        class: AppBundle\Model\Parser\Price\PriceParserFactory
        arguments:
            - '%bin.tomita%'
            - '%file.config.tomita.price%'

    parser.subway.factory:
        class: AppBundle\Model\Parser\Subway\SubwayParserFactory
        arguments:
            - "@odm.hot.data.mapper.factory"

    parser.datetime.factory:
        class: AppBundle\Model\Parser\DateTime\DateTimeParserFactory

    parser.description.factory:
        class: AppBundle\Model\Parser\Description\DescriptionParserFactory

    parser.photo.factory:
        class: AppBundle\Model\Parser\Photo\PhotoParserFactory


#parsers =============================================================


#explorers ===========================================================

    explorer.contact.factory:
        class: AppBundle\Model\Explorer\Contact\ContactExplorerFactory
        arguments:
            - "@client.http"

#explorers ===========================================================

#collectors =============================================================

    collector.factory:
        class: AppBundle\Model\Collector\CollectorFactory
        arguments:
            - '@client.http'
            - '%dir.tmp%'


#collectors =============================================================


    filter.unique.external_id:
        class: AppBundle\Model\Filter\ExternalIdUniqueFilter
        arguments:
            - "@odm.hot.data.mapper.factory"

    filter.active:
        class: AppBundle\Model\Filter\PostActiveFilter
        arguments:
            - "@odm.hot.data.mapper.factory"

    filter.black_list.description:
        class: AppBundle\Model\Filter\DescriptionBlackListFilter
        arguments:
            - "@odm.hot.data.mapper.factory"
            - "%file.black_list.description%"

    filter.black_list.person:
        class: AppBundle\Model\Filter\PersonBlackListFilter
        arguments:
            - "@odm.hot.data.mapper.factory"
            - "%file.black_list.person%"

    filter.expire.date:
        class: AppBundle\Model\Filter\DateExpireFilter

    filter.unique.description:
        class: AppBundle\Model\Filter\DescriptionUniqueFilter
        arguments:
            - "@odm.hot.data.mapper.factory"